/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*******************************************
*  AUTHOR IDENTITY
*
*  Initials    Name
*  --------    ----------------------------
*  ANR	       Aditya
********************************************/

#include <stdint.h>
#include "stm32f030xx.h"
#include "stm32f030xx_gpio_driver.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    GPIO_Handle_t GpioLed;

    GpioLed.pGPIOx = GPIOA;

    GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN5;

    GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT;

    GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_HI_SPEED;

    GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NOPUPD;

    GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_PUSH_PULL;

    // Enable Clock Control
    GPIO_PClockControl (GPIOA, ENABLE);

    // GPIO initialization
    GPIO_Init (&GpioLed);

    GPIO_WriteToOutputPin (GPIOA, GPIO_PIN5, GPIO_PIN_RESET);

    while (1)
    {
    	GPIO_ToggleOutputPin (GPIOA, GPIO_PIN5);

    	for (int i = 0; i <= 5000000; i++); /* Software Delay of approx ~7 seconds */
    }

    return 0;
}
